services:
  - type: web
    name: LaravelApp
    env: php
    plan: free  # Puedes elegir otro plan si lo necesitas
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force  # Esto aplicará las migraciones en producción
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        fromDatabase: true
